// <auto-generated> This file was generated by EF Core scaffolding. Manual changes may be overwritten.
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable enable

namespace FinanceAPI.Models;

[Table("Jewlery")]
public partial class Jewlery
{
    [Key]
    public int Id { get; set; }

    public int Owner { get; set; }

    [StringLength(10)]
    [Column(TypeName = "nchar(10)")]
    public string? Type { get; set; }

    [StringLength(100)]
    [Column(TypeName = "nchar(100)")]
    public string? Name { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? Weight { get; set; }

    [StringLength(10)]
    [Column(TypeName = "nchar(10)")]
    public string? WeightUnits { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? PurchasedPrice { get; set; }

    [StringLength(10)]
    [Column(TypeName = "nchar(10)")]
    public string? Currency { get; set; }

    public DateOnly? PurchasedDate { get; set; }

    public int? PurchasedFrom { get; set; }

    [StringLength(400)]
    [Column(TypeName = "nchar(200)")]
    public string? Description { get; set; }

    [ForeignKey("PurchasedFrom")]
    [InverseProperty("Jewleries")]
    public virtual Address? PurchasedFromNavigation { get; set; }

    // Navigation properties to related tables (if needed) can be added here.
}
